version: 2.1
 
workflows:
    Test:
        jobs:
            compile-run:
                docker:
                    - image: epitechcontent/epitest-docker
                steps:
                    - checkout
                    - run: make
                    - run: ./test.sh