version: 2.1
 
workflows:
    Test:
        jobs:
            - compile
                - build:
                    requires: 
                    - compile
 
jobs:
    compile:
        docker:
            - image: gcc:8.2
        steps:
            - checkout
            - run: make
 
    build:
        compile:
        docker:
            - image: epitechcontent/epitest-docker
        steps:
            - checkout
            - run: make
            - run: ./test.sh